dist: trusty
language: php

php:
  - 7.4

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4

before_install:
    # disable Xdebug if available
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    # disable default memory limit
    - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI
    - composer validate

install:
    # flags to pass to install
    - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
    # update deps to latest in case of high deps build
    - if [ "$deps" == "high" ]; then composer config platform.php 7.2.4; composer update $flags; fi
    # install dependencies using system provided composer binary
    - composer install $flags
    # install dependencies using composer from source
    - bin/composer install $flags

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
    - |
        if [[ $CODECOVERAGE == 1 ]]; then
          vendor/bin/phpunit --verbose --coverage-clover=clover.xml
        else
          vendor/bin/phpunit --verbose
        fi


after_success:
    - |
        if [[ $CODECOVERAGE == 1 ]]; then
          wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
          chmod +x php-coveralls.phar
          ./php-coveralls.phar
        fi
